// Generated by gencpp from file collvoid_msgs/AggregatedPoseTwist.msg
// DO NOT EDIT!


#ifndef COLLVOID_MSGS_MESSAGE_AGGREGATEDPOSETWIST_H
#define COLLVOID_MSGS_MESSAGE_AGGREGATEDPOSETWIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <collvoid_msgs/PoseTwistWithCovariance.h>

namespace collvoid_msgs
{
template <class ContainerAllocator>
struct AggregatedPoseTwist_
{
  typedef AggregatedPoseTwist_<ContainerAllocator> Type;

  AggregatedPoseTwist_()
    : header()
    , posetwists()  {
    }
  AggregatedPoseTwist_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , posetwists(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::collvoid_msgs::PoseTwistWithCovariance_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::collvoid_msgs::PoseTwistWithCovariance_<ContainerAllocator> >::other >  _posetwists_type;
  _posetwists_type posetwists;




  typedef boost::shared_ptr< ::collvoid_msgs::AggregatedPoseTwist_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::collvoid_msgs::AggregatedPoseTwist_<ContainerAllocator> const> ConstPtr;

}; // struct AggregatedPoseTwist_

typedef ::collvoid_msgs::AggregatedPoseTwist_<std::allocator<void> > AggregatedPoseTwist;

typedef boost::shared_ptr< ::collvoid_msgs::AggregatedPoseTwist > AggregatedPoseTwistPtr;
typedef boost::shared_ptr< ::collvoid_msgs::AggregatedPoseTwist const> AggregatedPoseTwistConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::collvoid_msgs::AggregatedPoseTwist_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::collvoid_msgs::AggregatedPoseTwist_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace collvoid_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'collvoid_msgs': ['/home/anton/catkin_ws/src/collvoid/collvoid_msgs/msg'], 'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::collvoid_msgs::AggregatedPoseTwist_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::collvoid_msgs::AggregatedPoseTwist_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::collvoid_msgs::AggregatedPoseTwist_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::collvoid_msgs::AggregatedPoseTwist_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::collvoid_msgs::AggregatedPoseTwist_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::collvoid_msgs::AggregatedPoseTwist_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::collvoid_msgs::AggregatedPoseTwist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b57a6e1f6dc93663d454cab62daa81a6";
  }

  static const char* value(const ::collvoid_msgs::AggregatedPoseTwist_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb57a6e1f6dc93663ULL;
  static const uint64_t static_value2 = 0xd454cab62daa81a6ULL;
};

template<class ContainerAllocator>
struct DataType< ::collvoid_msgs::AggregatedPoseTwist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "collvoid_msgs/AggregatedPoseTwist";
  }

  static const char* value(const ::collvoid_msgs::AggregatedPoseTwist_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::collvoid_msgs::AggregatedPoseTwist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
collvoid_msgs/PoseTwistWithCovariance[] posetwists\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: collvoid_msgs/PoseTwistWithCovariance\n\
Header header\n\
string robot_id\n\
float32 radius\n\
bool holo_robot\n\
bool controlled\n\
geometry_msgs/Vector3 holonomic_velocity\n\
geometry_msgs/PoseWithCovariance pose\n\
geometry_msgs/TwistWithCovariance twist\n\
geometry_msgs/PolygonStamped footprint\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
================================================================================\n\
MSG: geometry_msgs/PoseWithCovariance\n\
# This represents a pose in free space with uncertainty.\n\
\n\
Pose pose\n\
\n\
# Row-major representation of the 6x6 covariance matrix\n\
# The orientation parameters use a fixed-axis representation.\n\
# In order, the parameters are:\n\
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n\
float64[36] covariance\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: geometry_msgs/TwistWithCovariance\n\
# This expresses velocity in free space with uncertainty.\n\
\n\
Twist twist\n\
\n\
# Row-major representation of the 6x6 covariance matrix\n\
# The orientation parameters use a fixed-axis representation.\n\
# In order, the parameters are:\n\
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n\
float64[36] covariance\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Twist\n\
# This expresses velocity in free space broken into its linear and angular parts.\n\
Vector3  linear\n\
Vector3  angular\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PolygonStamped\n\
# This represents a Polygon with reference coordinate frame and timestamp\n\
Header header\n\
Polygon polygon\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Polygon\n\
#A specification of a polygon where the first and last points are assumed to be connected\n\
Point32[] points\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point32\n\
# This contains the position of a point in free space(with 32 bits of precision).\n\
# It is recommeded to use Point wherever possible instead of Point32.  \n\
# \n\
# This recommendation is to promote interoperability.  \n\
#\n\
# This message is designed to take up less space when sending\n\
# lots of points at once, as in the case of a PointCloud.  \n\
\n\
float32 x\n\
float32 y\n\
float32 z\n\
";
  }

  static const char* value(const ::collvoid_msgs::AggregatedPoseTwist_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::collvoid_msgs::AggregatedPoseTwist_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.posetwists);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AggregatedPoseTwist_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::collvoid_msgs::AggregatedPoseTwist_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::collvoid_msgs::AggregatedPoseTwist_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "posetwists[]" << std::endl;
    for (size_t i = 0; i < v.posetwists.size(); ++i)
    {
      s << indent << "  posetwists[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::collvoid_msgs::PoseTwistWithCovariance_<ContainerAllocator> >::stream(s, indent + "    ", v.posetwists[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // COLLVOID_MSGS_MESSAGE_AGGREGATEDPOSETWIST_H
