// Generated by gencpp from file collvoid_msgs/PoseArrayWeighted.msg
// DO NOT EDIT!


#ifndef COLLVOID_MSGS_MESSAGE_POSEARRAYWEIGHTED_H
#define COLLVOID_MSGS_MESSAGE_POSEARRAYWEIGHTED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>

namespace collvoid_msgs
{
template <class ContainerAllocator>
struct PoseArrayWeighted_
{
  typedef PoseArrayWeighted_<ContainerAllocator> Type;

  PoseArrayWeighted_()
    : header()
    , poses()
    , weights()  {
    }
  PoseArrayWeighted_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , poses(_alloc)
    , weights(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::geometry_msgs::Pose_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Pose_<ContainerAllocator> >::other >  _poses_type;
  _poses_type poses;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _weights_type;
  _weights_type weights;




  typedef boost::shared_ptr< ::collvoid_msgs::PoseArrayWeighted_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::collvoid_msgs::PoseArrayWeighted_<ContainerAllocator> const> ConstPtr;

}; // struct PoseArrayWeighted_

typedef ::collvoid_msgs::PoseArrayWeighted_<std::allocator<void> > PoseArrayWeighted;

typedef boost::shared_ptr< ::collvoid_msgs::PoseArrayWeighted > PoseArrayWeightedPtr;
typedef boost::shared_ptr< ::collvoid_msgs::PoseArrayWeighted const> PoseArrayWeightedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::collvoid_msgs::PoseArrayWeighted_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::collvoid_msgs::PoseArrayWeighted_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace collvoid_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'collvoid_msgs': ['/home/anton/catkin_ws/src/collvoid/collvoid_msgs/msg'], 'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::collvoid_msgs::PoseArrayWeighted_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::collvoid_msgs::PoseArrayWeighted_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::collvoid_msgs::PoseArrayWeighted_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::collvoid_msgs::PoseArrayWeighted_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::collvoid_msgs::PoseArrayWeighted_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::collvoid_msgs::PoseArrayWeighted_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::collvoid_msgs::PoseArrayWeighted_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0b8f62c9f0f1bef674fd5d702a22458d";
  }

  static const char* value(const ::collvoid_msgs::PoseArrayWeighted_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0b8f62c9f0f1bef6ULL;
  static const uint64_t static_value2 = 0x74fd5d702a22458dULL;
};

template<class ContainerAllocator>
struct DataType< ::collvoid_msgs::PoseArrayWeighted_<ContainerAllocator> >
{
  static const char* value()
  {
    return "collvoid_msgs/PoseArrayWeighted";
  }

  static const char* value(const ::collvoid_msgs::PoseArrayWeighted_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::collvoid_msgs::PoseArrayWeighted_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
geometry_msgs/Pose[] poses\n\
float32[] weights\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::collvoid_msgs::PoseArrayWeighted_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::collvoid_msgs::PoseArrayWeighted_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.poses);
      stream.next(m.weights);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoseArrayWeighted_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::collvoid_msgs::PoseArrayWeighted_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::collvoid_msgs::PoseArrayWeighted_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "poses[]" << std::endl;
    for (size_t i = 0; i < v.poses.size(); ++i)
    {
      s << indent << "  poses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "    ", v.poses[i]);
    }
    s << indent << "weights[]" << std::endl;
    for (size_t i = 0; i < v.weights.size(); ++i)
    {
      s << indent << "  weights[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.weights[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // COLLVOID_MSGS_MESSAGE_POSEARRAYWEIGHTED_H
