(cl:defpackage collvoid_msgs-msg
  (:use )
  (:export
   "<AGGREGATEDPOSETWIST>"
   "AGGREGATEDPOSETWIST"
   "<POSEARRAYWEIGHTED>"
   "POSEARRAYWEIGHTED"
   "<POSETWISTWITHCOVARIANCE>"
   "POSETWISTWITHCOVARIANCE"
   "<COLLVOID_DEBUG>"
   "COLLVOID_DEBUG"
  ))

